# Generated by Django 5.2.7 on 2025-10-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
